const mangaData = [
    { title: "Solo Leveling",
        image: "image/Manga/solo-leveling-1-190x273.jpg",
        description: "Jinwoo Sung, the weakest E-class hunter, discovers a hidden dungeon that changes his fate, unlocking a path to immense power.",
        isWeeklyPopular: true },

    { title: "Omniscient Reader's Viewpoint",
        image: "image/Manga/omniscient-readers-viewpoint-1-285x410.webp",
        description: "Dokja Kim, the sole reader of an obscure novel, must navigate a world turned into a deadly game, using his knowledge to survive.",
        isWeeklyPopular: true },

    { title: "Revenge of the Baskerville Bloodhound",
        image: "image/Manga/revenge-of-the-baskerville-bloodhound-1-285x399.webp",
        description: "Betrayed and killed by his father, Vikir is reborn and vows to rise above his assassin family to exact revenge.",
        isWeeklyPopular: false },
    { title: "The Greatest Estate Developer",
        image: "image/Manga/the-greatest-estate-developer-1-285x398.jpg",
        description: "Suho Kim wakes up as Lloyd Frontera in a fantasy world and uses his engineering skills to rescue his family from debt.",
        isWeeklyPopular: false },
    { title: "Chainsaw Man",
        image: "image/Manga/chainsaw-man-1-285x428.jpg",
        description:"Denji's life of poverty is changed forever when he merges with his pet chainsaw dog, Pochita! Now he's living in the big city and an official Devil Hunter. But he's got a lot to learn about his new job and chainsaw powers!",
        isWeeklyPopular : true },
    { title: "The Beginning After the End",
        image: "image/Manga/the-beginning-after-the-end-1-285x409.webp",
        description:"A powerful king reincarnates in a magical world, seeking purpose while confronting hidden threats.",
        isWeeklyPopular : true },

    { title: "Nano Machine",
        image: "image/Manga/nano-machine-1-285x400.webp",
        description:"Yeo-un gains futuristic nanomachines, helping him rise in the deadly competition to become the Minor Priest.",
        isWeeklyPopular : true },
    { title: "The Extra's Academy Survival Guide",
        image: "image/Manga/the-extras-academy-survival-guide-1-285x399.webp",
        description:"Waking up as a game’s third-rate villain, Ed Rothstaylor must earn a scholarship and avoid altering the story.",
        isWeeklyPopular : false },
    { title: "The Swordmaster's Son",
        image: "image/Manga/the-swordmasters-son-1-285x399.webp",
        description:"Banished for poor swordsmanship, Jin Runcandel is reborn and vows to fulfill his destiny as a swordmaster.",
        isWeeklyPopular : true },
    { title: "The Infinite Mage",
        image: "image/Manga/the-infinite-mage-1-285x399.webp",
        description:"Born a peasant, Sirone defies the odds to become a powerful mage, challenging noble traditions.",
        isWeeklyPopular : false },
    { title: "Pick Me Up",
        image: "image/Manga/pick-me-up-1-285x399.webp",
        description:"Seojin Han becomes a 1-star hero in a brutal game, fighting to defeat the player controlling his fate.",
        isWeeklyPopular : true },
    { title: "Dandadan",
        image: "image/Manga/dandadan-1-285x428.webp",
        description: "Momo Ayase and Okarun explore paranormal events, forming an unlikely bond in their supernatural battles.",
        isWeeklyPopular :  true},
    { title: "The Reborn Young Lord is an Assassin",
        image: "image/Manga/the-reborn-young-lord-is-an-assassin-1-285x399.webp",
        description:"Reborn as a child, Cyan Vert plans to escape his brother’s shadow and forge his own powerful legacy.",
        isWeeklyPopular :true  },
    { title: "Eleceed",
        image: "image/Manga/eleceed-1-190x266.jpg",
        description:"Jiwoo and a secret agent-turned-cat team up to protect the world with speed and strategy.",
        isWeeklyPopular : false },
    { title: "I'm the Max-Level Newbie",
        image: "image/Manga/im-the-max-level-newbie-1-285x399.webp",
        description:"Streamer Kang Jinhyeok uses his game knowledge to survive when the Tower of Trials becomes reality.",
        isWeeklyPopular : true },
    { title: "Solo Leveling: Ragnarok",
        image: "image/Manga/solo-leveling-ragnarok-1-285x399.webp",
        description:"Streamer Kang Jinhyeok uses his game knowledge to survive when the Tower of Trials becomes reality.",
        isWeeklyPopular :  true},

    { title: "One Piece",
        image: "image/Manga/one-piece-1-285x432.jpg",
        description: "Luffy sets sail to find One Piece and become the Pirate King.",
        isWeeklyPopular : true },
    { title: "The Return of the Disaster-Class Hero",
        image: "image/Manga/the-return-of-the-disaster-class-hero-1-285x399.webp",
        description:"Betrayed hero Geon Lee returns stronger to fight his enemies.",
        isWeeklyPopular : true },
    { title: "The Martial God Who Regressed Back to Level 2",
        image: "image/Manga/the-martial-god-who-regressed-back-to-level-2-1-285x399.webp",
        description:"Jihan Seong rewinds time to save humanity from BattleNet.",
        isWeeklyPopular :  true},
    { title: "Myst, Might, Mayhem",
        image: "image/Manga/myst-might-mayhem-1-285x399.webp",
        description:"Jeong seeks revenge for his grandfather's murder.",
         isWeeklyPopular : false },
    { title: "The Novel's Extra (2022)",
        image: "image/Manga/the-novels-extra-2022-1-285x399.webp",
        description:"Kim Hajin is trapped as an extra in his own novel.",
        isWeeklyPopular : false },
    { title: "The Academy's Genius Swordsman",
        image: "image/Manga/the-academys-genius-swordsman-1-285x400.webp",
        description:"Ronan travels back in time to become the strongest swordsman.",
        isWeeklyPopular : true },
    { title: "Return of the Mad Demon",
        image: "image/Manga/return-of-the-mad-demon-1-285x399.jpg",
        description:"Jaha Lee gets a second chance to become the God of Martial Arts.",
        isWeeklyPopular : false },
    { title: "SSS-Class Revival Hunter",
        image: "image/Manga/sss-class-revival-hunter-1-285x399.webp",
        description:"Confucius Kim can copy skills after being killed by others.",
        isWeeklyPopular : true },
    { title: "Jujutsu Kaisen",
        image: "image/Manga/jujutsu-kaisen-1-285x411.webp",
        description: "Yuji Itadori battles curses after swallowing a cursed object.",
         isWeeklyPopular : true },
    { title: "SPY x FAMILY",
        image: "image/Manga/spy-x-family-1-285x427.jpg",
        description:"Spy Twilight must build a fake family for a mission.",
        isWeeklyPopular : true },
    { title: "Second Life Ranker",
        image: "image/Manga/second-life-ranker-1-285x398.jpg",
        description:"Yeonwoo climbs the Tower to avenge his brother.",
        isWeeklyPopular : true },
    { title: "A Flame Reborn",
        image: "image/Manga/a-flame-reborn-1-285x399.webp",
        description:"Knight Logan is reborn to avenge his brother and save his kingdom.",
        isWeeklyPopular :false  },
    { title: "The Reincarnated Assassin Is a Swordmaster",
        image: "image/Manga/the-reincarnated-assassin-is-a-swordmaster-1-285x399.webp",
        description:"Raon is reborn to seek revenge with his new noble power.", 
        isWeeklyPopular : false },
    { title: "Black Clover",
        image: "image/Manga/black-clover-1-285x428.webp",
        description: "Magicless Asta dreams of becoming the Wizard King.",
        isWeeklyPopular :true},
    { title: "One-Punch Man",
        image: "image/Manga/one-punch-man-1-285x428.webp",
        description:"Saitama defeats enemies with a single punch, seeking a challenge.",
        isWeeklyPopular : false },
    { title: "The Servant Is the Demon King?!",
        image: "image/Manga/the-servant-is-the-demon-king-1-285x399.webp",
        description: "Demon King Yifan reincarnates as a servant tied to Lady Luo."},
];